---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Create data directory
  file:
    path: '{{ elasticsearch_data_path }}'
    state: directory
    owner: elasticsearch
    group: elasticsearch
  when: elasticsearch_data_path is defined

- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch

- name: Configure JAVA_HOME
  become: true
  lineinfile:
    dest: '{{ elasticsearch_env_path }}'
    regexp: '^JAVA_HOME='
    line: 'JAVA_HOME={{ elasticsearch_java_home }}'
    state: present
  notify: restart elasticsearch
  when: elasticsearch_java_home is defined

- name: Start Elasticsearch.
  service: name=elasticsearch state=started enabled=yes

- name: Make sure Elasticsearch is running before proceeding.
  wait_for: port={{ elasticsearch_http_port }} delay=3 timeout=300
